import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import '../models/clinical_atom.dart';
import '../objectbox.g.dart'; // This file will be generated by build_runner
import 'db_crypto_service.dart';

/// ═══════════════════════════════════════════════════════════════════
///  Encrypted ObjectBox Service
/// ═══════════════════════════════════════════════════════════════════
///
///  Privacy-first local clinical database.
///
///  All sensitive PHI (Protected Health Information) fields — name,
///  value, unit, and metadata — are encrypted with AES-256-GCM at
///  the application layer before being written to ObjectBox.
///
///  The 'type' and 'date' fields remain in plaintext to preserve
///  ObjectBox index-based query performance (e.g. "find all
///  medications" or "records from last 30 days").
///
///  Encryption key is stored in flutter_secure_storage, backed by
///  Android Keystore / iOS Keychain hardware security module.
/// ═══════════════════════════════════════════════════════════════════
class ObjectBoxService {
  late final Store store;
  late final Box<ClinicalAtom> atomBox;

  ObjectBoxService._create(this.store) {
    atomBox = Box<ClinicalAtom>(store);
  }

  /// Create an instance of ObjectBox to use throughout the app.
  /// Initializes the encryption service before opening the store.
  static Future<ObjectBoxService> create() async {
    // Initialize the encryption key (generates on first launch)
    await DbCryptoService.init();

    final docsDir = await getApplicationDocumentsDirectory();
    final store = await openStore(directory: p.join(docsDir.path, "curenet-clinical-db"));
    return ObjectBoxService._create(store);
  }

  /// Save a single clinical atom with encryption.
  Future<void> saveAtom(ClinicalAtom atom) async {
    final encrypted = await _encryptAtom(atom);
    atomBox.put(encrypted);
  }

  /// Save multiple clinical atoms with encryption.
  Future<void> saveAtoms(List<ClinicalAtom> atoms) async {
    final encrypted = await Future.wait(atoms.map(_encryptAtom));
    atomBox.putMany(encrypted);
  }

  /// Retrieve all clinical atoms, decrypting sensitive fields.
  Future<List<ClinicalAtom>> getAllAtoms() async {
    final raw = atomBox.getAll();
    return Future.wait(raw.map(_decryptAtom));
  }

  /// Query atoms by type (type field is NOT encrypted — index-friendly).
  Future<List<ClinicalAtom>> findAtomsByType(String type) async {
    final query = atomBox.query(ClinicalAtom_.type.equals(type)).build();
    final raw = query.find();
    query.close();
    return Future.wait(raw.map(_decryptAtom));
  }

  /// Remove all stored atoms.
  void clearAll() {
    atomBox.removeAll();
  }

  // ─── Encryption Helpers ──────────────────────────────────────────

  /// Encrypt sensitive PHI fields before persisting to ObjectBox.
  /// Leaves 'type' and 'date' in plaintext for query indexing.
  Future<ClinicalAtom> _encryptAtom(ClinicalAtom atom) async {
    return ClinicalAtom(
      type: atom.type,                                          // plaintext (indexed)
      name: await DbCryptoService.encrypt(atom.name),           // encrypted
      value: await DbCryptoService.encrypt(atom.value),         // encrypted
      unit: await DbCryptoService.encrypt(atom.unit),           // encrypted
      date: atom.date,                                          // plaintext (indexed)
      metadataJson: await DbCryptoService.encrypt(atom.metadataJson), // encrypted
    )..id = atom.id;
  }

  /// Decrypt sensitive PHI fields after reading from ObjectBox.
  /// Gracefully handles unencrypted legacy data (returns as-is).
  Future<ClinicalAtom> _decryptAtom(ClinicalAtom atom) async {
    return ClinicalAtom(
      type: atom.type,
      name: await DbCryptoService.decrypt(atom.name),
      value: await DbCryptoService.decrypt(atom.value),
      unit: await DbCryptoService.decrypt(atom.unit),
      date: atom.date,
      metadataJson: await DbCryptoService.decrypt(atom.metadataJson),
    )..id = atom.id;
  }
}
